const widgetsMap = {
  'com.fliplet.menu.bottom-bar': 'menuBottom',
  'com.fliplet.menu.expandable': 'menuCircle',
  'com.fliplet.menu.default': 'menuOverlay',
  'com.fliplet.menu.push-in': 'menuPushIn',
  'com.fliplet.menu.slide-in': 'menuSlideIn',
  'com.fliplet.menu.sequential': 'menuSwipe',
  'app-list': 'appList',
  'com.fliplet.accordionstart': 'accordion',
  'com.fliplet.accordionend': 'accordion',
  'com.fliplet.data-directory': 'directory',
  'com.fliplet.advanceddirectory': 'advancedDirectory',
  'com.fliplet.chart.bar': 'chartBar',
  'com.fliplet.chart.column': 'chartColumn',
  'com.fliplet.chart.scatter': 'charScatter',
  'com.fliplet.chart.line': 'chartLine',
  'com.fliplet.chart.donut': 'chartDonut',
  'com.fliplet.chart.pie': 'chartPie',
  'com.fliplet.login': 'login',
  'com.fliplet.login-data-source': 'loginDataSource',
  'com.fliplet.login.saml2': 'loginSaml',
  'com.fliplet.lock': 'lock',
  'com.fliplet.email-validation': 'emailVerification',
  'com.fliplet.sms-verfication': 'smsVerification',
  'com.fliplet.image': 'image',
  'masonry-image-gallery': 'imageGallery',
  'com.fliplet.chat': 'chat',
  'com.fliplet.form-builder': 'formBuilder',
  'com.fliplet.interactive-map': 'interactiveGraphics',
  'com.fliplet.simple-list': 'list',
  'com.fliplet.list-small-thumbs': 'listSmallThumbs',
  'com.fliplet.list-large-thumbs': 'listLargeThumbs',
  'com.fliplet.dynamic-lists': 'lfd',
  'com.fliplet.panels': 'panels',
  'com.fliplet.metro': 'grid',
  'com.fliplet.rss': 'rss',
  'com.fliplet.primary-button': 'primaryButton',
  'com.fliplet.secondary-button': 'secondaryButton',
  'com.fliplet.inline-link': 'inlineLink',
  'com.fliplet.online-offline': 'offlineVideo',
  'com.fliplet.online-video': 'onlineVideo',
  'com.fliplet.notificationinbox': 'notificationBox',
  'com.fliplet.photo-sharing': 'photoSharing',
  'com.fliplet.onboarding': 'onboarding',
  'com.fliplet.slider': 'slider'
}

export default widgetsMap